### ISSUE TITLE
relative stylesheet link

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#16]
The link to the stylesheet should be relative, so it will work if served via more than one path

**Comment by RalfJung** [comment]
The link to the stylesheet is deliberately absolute because there may be subdirectories at some point. E.g. `http://server/node-monitor/foo/bar` should be able to use the same template as the current pages. With a relative stylesheet path, that will not work.

I could make the stylesheet path configurable separately from the root URL, so one could make it `/node-monitor/static/style.css` instead of `http://server/node-monitor/static/style.css`. Would that be sufficient for your usecase?

**Comment by rubo77** [comment]
It should be relative to the root folder of the site then. 

Without HTTP://domain:port/ 

Then it would work from http://localhost and http://somewhat.org too

**Comment by RalfJung** [comment]
node-monitor sends emails and has to put a link into them. That link can't be relative at all. So, your setup would still not work properly, right?

**Comment by rubo77** [comment]
You need two config values:

-the base URL
-the path (/ or /subpath/ )
The CSS only needs the subpath in its src

**Comment by RalfJung** [comment]
What I am saying is, having two config values makes things more complicated and doesn't really help. Let's say we had this second value. Now you have node-monitor available on two paths. You add a node, it sends an email. We still have to pick a particular path for that email, a path that works always for all users. Why not just use that path for CSS as well?

**Comment by RalfJung** [comment]
I will close this for now as I don't see how this can help; if you have further information please reopen.
