### ISSUE TITLE
Add info after time of alert

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#30]
Please add information to the Readme, after which time offline you get automatically alerted by email, that your node is offline and how often you get alerted

**Comment by RalfJung** [comment]
> that there is sent out an email EVERY time a node status changes, is that correct?

That is correct.

However, this is using the online status from hopglass. Hopglass does some filtering already. When a node of mine goes online I get a mail within 5min, but when it goes offline it takes up to 30min -- presumably because hopglass waits to make sure the node is really offline.

So, I don't think we need to do any extra filtering on our side. And unfortunately I do not know how long hopglass waits before marking nodes as offline -- you'd have to ask them. :)
