### ISSUE TITLE
How to add the outer frame if included as iframe

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#31]
I included the node-monitor here: https://freifunk.in-kiel.de/knotenalarm.html

That site includes the node-monitor in an iframe. all emails sent are linking to the site just in that iframe: https://freifunk.in-kiel.de/knotenalarm/ , Which misses our outer frame.

Not sure, how to solve this problem.

I would like to open the site in a frame, but that would only be possible with a cookie set in the node-monitor, i guess

**Comment by rubo77** [comment]
Or we add a simple header with a link to the startpage at the top with javascript, that only shows that header if loaded without being in an iframe:

```
if (window.frameElement) {
  // in frame
}
else {
  // not in frame
}
```

**Comment by RalfJung** [comment]
This is one of the reasons frames are bad -- you can't meaningfully link to things inside a frame.

I don't really understand what you are proposing in your second post.

Personally I'd just not use a frame. I will not work myself on improving support for framed use, but if you find a good way, feel free to submit a PR. One thing I could imagine:
* Script your `knotenalarm.html` such that one can go to `knotenalarm.html?page=list.html` which will then navigate the frame to that other site (with appropriate encoding of URL characters).
* Set up a redirect that turns `knotenalarm/list.html?foo=bar` into `knotenalarm.html?page=list.html%3Ffoo%3Dbar`.

If you want, we can keep this issue open, but I will mark it as "wontfix" because I will not be working towards fixing it.

**Comment by RalfJung** [comment]
At least until this is resolved, I have removed mentioning the iframe from the README. I think the better way to integrate this is to just use a link (at least, that's what we are doing).

**Comment by rubo77** [comment]
There should be some hint how to adapt it to the local CI.

If not with an iframe, then it should be a hint, how to adapt the Theme, so you get a Freifunk Logo and a backlink to the homepage at the top and so on

**Comment by rubo77** [comment]
> The config key to add additional CSS is described in Rocket.toml.dist.

Then there should be an example, how to change the CSS in the README

**Comment by RalfJung** [comment]
> I think a CSS example how to add the community Logo would be most helpful too

Would you like to provide such an example?

**Comment by rubo77** [comment]
done: #39

**Comment by RalfJung** [comment]
> done: #39

Closing this issue then.
