### ISSUE TITLE
 Error: Database configuration failure: 'postgres'

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#62]
After migrating to a new server, and importing and upgrading Postgres to v11 i get this error: 

```
Error: Database configuration failure: 'postgres'
Jul 02 09:42:27 freifunk ff-node-monitor[22562]: Error: A table named `databases` was not found for this configuration
Jul 02 09:42:27 freifunk ff-node-monitor[22562]: thread 'main' panicked at 'could not connect to DB for migrations', src/libcore/option.rs:1036:5

**Comment by RalfJung** [comment]
I don't see a ff-node-monitor bug here. Looks like the database does not exist?

I have had issues with Postgres migration before. But I'm afraid I don't know enough about Postgres to provide support for it.

**Comment by rubo77** [comment]
It seems like a problem with the connection string, maybe due to che changes in your changelog: https://github.com/freifunk-saar/ff-node-monitor/blob/master/CHANGELOG.md

**Comment by RalfJung** [comment]
> which is strange, because there is no such file /var/run/postgresql/.s.PGSQL.5432 but /var/run/postgresql/.s.PGSQL.5433

Ah, I had this before... this is the port used by postgres. In debian, a new postgres doesn't *replace* the old one, it gets installed alongside, so the new postgres has to pick a different port number. Of course one uninstalls the old postgres after migration, but at that point the new postgres already has its port number set and it won't change automatically.

(Btw, I almost missed most of your post since I only read the email notification. When adding significant information, please always make a new post instead of editing an old one, unless you want to risk email users to just not see your edits.)

**Comment by rubo77** [comment]
I didn't find an option for the postgresql Port in `Rocket.toml`, so I changed the postgresql port.  You'll find the port config in `/etc/postgresql/11/main/postgresql.conf`

JUHUUU!

That was it, it is up and running again: https://freifunk.in-kiel.de/knotenalarm.html
